[package]
name = "advent2024"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
benchmarking = "0.4.13"
itertools = "0.13.0"
num-rational = "0.4.2"
regex = "1.11.1"

[profile.test]
inherits = "release"

